regrs:
	cd $$SOCROOT/verif/tests/irq_test && make run
	cd $$SOCROOT/verif/tests/ahb_infra_test && make run

clean:
	cd $$SOCROOT/verif/tests/irq_test && make clean
	cd $$SOCROOT/verif/tests/ahb_infra_test && make clean

.PHONY: regrs clean
