[library.MVU]
location = ip/MVU
sync-uri = git@github.com:thomas6785/MVU.git
sync-type = git
auto-sync = true

[library.Ibex]
location = /home/tudentstudent/DyNNSoC/ip/ibex
sync-uri = ip/ibex
sync-type = local
auto-sync = true

[library..]
location = /home/tudentstudent/DyNNSoC
sync-uri = .
sync-type = local
auto-sync = true

