[library.ibex]
location = /home/tudentstudent/DyNNSoC/ip/ibex
sync-uri = ./ip/ibex/
sync-type = local
auto-sync = true

[library.MVU]
location = ./ip/MVU
sync-uri = https://github.com/thomas6785/MVU.git
sync-type = git
auto-sync = true

